import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false}});
const $=id=>document.getElementById(id);
const PLANTS={treeGun:{name:"Tree Gun",cost:75,hp:100,damage:24,rate:1.15,img:"../assets/plant-tree-gun.png"},rosegun:{name:"Rosegun",cost:50,hp:65,damage:12,rate:1,img:"../assets/rosegun.png"},bucketStalk:{name:"Bucket-Stalk",cost:165,hp:115,damage:72,rate:2.05,img:"../assets/bucketboi.png"},cloudPopper:{name:"Cloud Popper",cost:125,hp:90,damage:27,rate:.95,img:"../assets/cloudpopper.png"},starfruit:{name:"Starfruit Knockoff",cost:175,hp:90,damage:22,rate:1.5,img:"../assets/starfruitknockoff.png"},cardboard:{name:"Cardboard Wall",cost:35,hp:145,damage:0,rate:9,img:"../assets/cardboardwall.png"},mattress:{name:"Soggy Mattress",cost:50,hp:190,damage:0,rate:9,img:"../assets/soggy-mattress.png"},fridge:{name:"Rusty Fridge",cost:150,hp:520,damage:0,rate:9,img:"../assets/rustyfridge.png"},kaboom:{name:"El Kaboom",cost:225,hp:40,damage:190,rate:5,img:"../assets/plant-el-kaboom.png"},moss:{name:"Moss Cannon",cost:115,hp:105,damage:26,rate:1.25,img:"../assets/plant-moss-cannon.png"},darkMissile:{name:"Dark Missile Cannon",cost:240,hp:90,damage:95,rate:3.2,img:"../assets/plant-dark-missile-cannon.png"},burningEye:{name:"Burning Eye",cost:185,hp:80,damage:48,rate:1.7,img:"../assets/plant-burning-eye.png"}};
const DERPS={basic:{name:"Da Boiiiiii",cost:70,hp:90,speed:.58,damage:10,img:"../assets/enemy-basic-derp.png"},armored:{name:"Armored Boi",cost:130,hp:190,speed:.42,damage:16,img:"../assets/enemy-armored-derp.png"},fast:{name:"Fast Boi",cost:85,hp:65,speed:1.05,damage:8,img:"../assets/enemy-fast-derp.png"},assassin:{name:"Assasin Rover",cost:100,hp:1,speed:1.4,damage:50,img:"../assets/assasin-rover.png"},droneGun:{name:"Drone Gun",cost:135,hp:105,speed:.62,damage:12,img:"../assets/dronegun.png"},droneSaw:{name:"Drone Saw",cost:105,hp:75,speed:1.15,damage:22,img:"../assets/dronesaw.png"},alien:{name:"Odd Alien",cost:110,hp:130,speed:.52,damage:12,img:"../assets/alien.png"},alienGun:{name:"Alien Gunner",cost:150,hp:155,speed:.39,damage:16,img:"../assets/aliengun.png"},clown:{name:"Clown Derp",cost:125,hp:140,speed:.7,damage:15,img:"../assets/enemy-clown-derp.png"},clownCar:{name:"Clown Car",cost:260,hp:360,speed:.55,damage:28,img:"../assets/enemy-clown-car.png"},puppet:{name:"Puppet Derp",cost:145,hp:145,speed:.68,damage:18,img:"../assets/enemy-puppet-derp.png"},curse:{name:"Curse of the Derp",cost:210,hp:240,speed:.5,damage:30,img:"../assets/enemy-curse-of-the-derp.png"}};
const BACKGROUNDS={forest:"Forest",desert:"Desert",cloud:"Cloud",milkyway:"Milky Way",clownBrown:"Clown Brown",clownChaos:"Clown Chaos",clownTeal:"Clown Teal",clownGreen:"Clown Green",clownBlood:"Blood Clown Moon",edge:"The Edge"};
const BG_PATH={forest:"../assets/bg-forest.png",desert:"../assets/bg-desert.png",cloud:"../assets/bg-cloud.png",milkyway:"../assets/bg-milkyway.png",clownBrown:"../assets/bg-clown-brown.png",clownChaos:"../assets/bg-clown-chaos.png",clownTeal:"../assets/bg-clown-teal.png",clownGreen:"../assets/bg-clown-green.png",clownBlood:"../assets/bg-clown-blood.png",edge:"../assets/bg-the-edge.png"};

let mode="online",channel=null,localChannel=null,roomCode="",me=null,isHost=false,members=new Map(),assigned=[],settings=null,loadouts={},rerolls={},readyMap={},selectedSlot=0,gameState=null,simTimer=null,lastActionAt={},kicked=false;
const clean=v=>String(v||"").replace(/[<>]/g,"").trim();const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);const code=()=>Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join("");
function log(s){const e=document.createElement("div");e.textContent=`[${new Date().toLocaleTimeString()}] ${s}`;$("lobbyLog").prepend(e)}
function send(event,payload){if(mode==="online")return channel?.send({type:"broadcast",event,payload});localChannel?.postMessage({event,payload});}
function shuffledKeys(o){return Object.keys(o).sort(()=>Math.random()-.5)}
function makeLoadout(side){const src=side==="plants"?PLANTS:DERPS;return shuffledKeys(src).slice(0,6)}
function chooseRoles(list){if(list.length<2)return list;let p=list.find(x=>x.preference==="plants"),d=list.find(x=>x.preference==="derps"&&x.id!==p?.id);if(!p)p=list.find(x=>x.id!==d?.id);if(!d)d=list.find(x=>x.id!==p?.id);return list.map(x=>({...x,side:x.id===p.id?"plants":"derps"}));}
function renderPlayers(){const list=assigned.length?assigned:[...members.values()];$("players").innerHTML=list.map(p=>`<div class="player"><span><b>${clean(p.name)}</b><small>${p.host?"Host • ":""}${p.side||p.preference}</small></span><span>${readyMap[p.id]?"READY":"not ready"}</span></div>`).join("");$("connectionBadge").textContent=list.length>=2?"2 PLAYERS CONNECTED":"WAITING";$("connectionBadge").className=`badge ${list.length>=2?"online":"waiting"}`;}
function unitCard(id,side,i,selectable=true){const u=(side==="plants"?PLANTS:DERPS)[id];return `<button class="unit-card ${selectable&&i===selectedSlot?"selected":""}" data-slot="${i}"><img src="${u.img}"><b>${u.name}</b><small>${u.cost} Glow • HP ${u.hp}</small></button>`}
function renderLoadout(){if(!me?.side||!loadouts[me.side])return;$("loadout").innerHTML=loadouts[me.side].map((id,i)=>unitCard(id,me.side,i)).join("");$("loadout").querySelectorAll(".unit-card").forEach(b=>b.onclick=()=>{selectedSlot=+b.dataset.slot;renderLoadout()});$("rerolls").textContent=rerolls[me.id]??3;}
function settingsText(){if(!settings)return "";return `<b>${settings.minutes} min • ${settings.glow} Glow</b><br>${BACKGROUNDS[settings.background]||settings.background}`}
function updateLobby(){renderPlayers();renderLoadout();$("matchSettings").innerHTML=settingsText();}
function hostPrepare(){assigned=chooseRoles([...members.values()]);for(const p of assigned){if(!loadouts[p.side])loadouts[p.side]=makeLoadout(p.side);rerolls[p.id]??=3;readyMap[p.id]??=false}send("lobby-state",{assigned,settings,loadouts,rerolls,readyMap});updateLobby()}
function receive(event,p={}){if(event==="hello"){members.set(p.id,p);if(isHost){send("hello-ack",me);hostPrepare()}}else if(event==="hello-ack"){members.set(p.id,p)}else if(event==="lobby-state"){assigned=p.assigned||assigned;settings=p.settings||settings;loadouts=p.loadouts||loadouts;rerolls=p.rerolls||rerolls;readyMap=p.readyMap||readyMap;me.side=assigned.find(x=>x.id===me.id)?.side;updateLobby()}else if(event==="reroll-request"&&isHost){handleReroll(p)}else if(event==="ready-change"&&isHost){readyMap[p.id]=!!p.ready;hostPrepare();if(assigned.length>=2&&assigned.every(x=>readyMap[x.id]))startGame()}else if(event==="start-game"){startClientGame(p.state)}else if(event==="intent"&&isHost){validateIntent(p)}else if(event==="snapshot"){gameState=p.state;renderGame()}else if(event==="round-kick"){if(p.id===me.id){kicked=true;endRound("Kicked from round",p.reason)}else log(`${p.name||"Player"} was kicked: ${p.reason}`)}else if(event==="round-end"){endRound(p.title,p.text)}else if(event==="forfeit"&&isHost){finish(p.side==="plants"?"Derps win":"Plants win",`${p.side} forfeited.`)}}
function openLobby(){$("setup").classList.add("hidden");$("lobby").classList.remove("hidden");$("roomCode").textContent=roomCode;updateLobby()}
async function online(host){mode="online";isHost=host;openLobby();channel=supabase.channel(`pad-pvp-${roomCode}`,{config:{presence:{key:me.id},broadcast:{self:true}}});["hello","hello-ack","lobby-state","reroll-request","ready-change","start-game","intent","snapshot","round-kick","round-end","forfeit"].forEach(ev=>channel.on("broadcast",{event:ev},({payload})=>receive(ev,payload)));channel.on("presence",{event:"sync"},()=>{for(const x of Object.values(channel.presenceState()).flat()){if(x.user)members.set(x.user.id,x.user)}if(isHost)hostPrepare();else updateLobby()});channel.subscribe(async st=>{if(st==="SUBSCRIBED"){await channel.track({user:me});send("hello",me);log("Connected online.")}else if(["CHANNEL_ERROR","TIMED_OUT"].includes(st))log(`Connection ${st}`)});}
function local(host){mode="local";isHost=host;openLobby();localChannel=new BroadcastChannel(`pad-pvp-${roomCode}`);localChannel.onmessage=e=>receive(e.data?.event,e.data?.payload);members.set(me.id,me);send("hello",me);if(isHost)hostPrepare();}
function enter(host,localMode){isHost=host;roomCode=host?code():clean($("joinCode").value).toUpperCase();if(!roomCode)return alert("Enter a join code.");me={id:uid(),name:clean($(host?"hostName":"guestName").value)||"Kitteh",preference:host?$("hostSide").value:"random",host};members.set(me.id,me);if(host)settings={minutes:+$("timeLimit").value,glow:+$("startGlow").value,background:$("backgroundSelect").value};localMode?local(host):online(host)}
function handleReroll(p){if(!assigned.find(x=>x.id===p.id)||rerolls[p.id]<=0)return kick(p.id,"invalid reroll");const side=assigned.find(x=>x.id===p.id).side;if(!Number.isInteger(p.slot)||p.slot<0||p.slot>=6)return kick(p.id,"invalid reroll slot");const src=side==="plants"?PLANTS:DERPS;let choices=Object.keys(src).filter(x=>!loadouts[side].includes(x));if(!choices.length)choices=Object.keys(src);loadouts[side][p.slot]=choices[Math.floor(Math.random()*choices.length)];rerolls[p.id]--;readyMap[p.id]=false;hostPrepare()}
function kick(id,reason){const p=assigned.find(x=>x.id===id);send("round-kick",{id,reason,name:p?.name});if(gameState){gameState.kicked=id;finish(p?.side==="plants"?"Derps win":"Plants win",`${p?.name||"Player"} was kicked: ${reason}`)}}
function startGame(){const state={startedAt:Date.now(),endsAt:Date.now()+settings.minutes*60000,settings,glow:{plants:settings.glow,derps:settings.glow},plants:[],derps:[],winner:null,nextId:1,cooldowns:{},lastTick:Date.now()};send("start-game",{state});startClientGame(state);if(isHost){simTimer=setInterval(hostTick,200)}}
function startClientGame(state){gameState=state;$("lobby").classList.add("hidden");$("game").classList.remove("hidden");$("battlefield").style.backgroundImage=`url('${BG_PATH[state.settings.background]}')`;$("sideLabel").textContent=(me.side||"?").toUpperCase();renderTray();renderGame()}
function renderTray(){const arr=loadouts[me.side]||[];$("unitTray").innerHTML=arr.map((id,i)=>unitCard(id,me.side,i,false)).join("");$("unitTray").querySelectorAll(".unit-card").forEach((b,i)=>b.onclick=()=>{selectedSlot=i;renderTray()});$("controlTitle").textContent=me.side==="plants"?"Place Plants":"Deploy Derps";$("controlHint").textContent=me.side==="plants"?"Select a unit, then click a tile in the left six columns.":"Select a derp, then click any tile in the lane you want."}
function actionRateOk(id){const now=Date.now(),last=lastActionAt[id]||0;lastActionAt[id]=now;return now-last>=180}
function validateIntent(p){if(!gameState||gameState.winner)return kick(p.playerId,"action outside active round");const person=assigned.find(x=>x.id===p.playerId);if(!person)return kick(p.playerId,"unknown player");if(person.side!==p.side)return kick(p.playerId,"spoofed side");if(!actionRateOk(p.playerId))return kick(p.playerId,"action spam");if(!Number.isInteger(p.slot)||p.slot<0||p.slot>=6)return kick(p.playerId,"invalid loadout slot");const id=loadouts[p.side]?.[p.slot],src=p.side==="plants"?PLANTS:DERPS,u=src[id];if(!u)return kick(p.playerId,"unit not in loadout");if(gameState.glow[p.side]<u.cost)return kick(p.playerId,"impossible Glow spend");const cdKey=`${p.playerId}:${p.slot}`,now=Date.now();if((gameState.cooldowns[cdKey]||0)>now)return kick(p.playerId,"cooldown bypass");gameState.cooldowns[cdKey]=now+500;if(p.side==="plants"){if(!Number.isInteger(p.row)||!Number.isInteger(p.col)||p.row<0||p.row>4||p.col<0||p.col>5)return kick(p.playerId,"invalid plant tile");if(gameState.plants.some(x=>x.row===p.row&&x.col===p.col&&x.hp>0))return;gameState.plants.push({eid:gameState.nextId++,type:id,row:p.row,col:p.col,hp:u.hp,maxHp:u.hp,lastShot:0})}else{if(!Number.isInteger(p.row)||p.row<0||p.row>4)return kick(p.playerId,"invalid derp lane");gameState.derps.push({eid:gameState.nextId++,type:id,row:p.row,x:8.7,hp:u.hp,maxHp:u.hp,lastHit:0})}gameState.glow[p.side]-=u.cost;send("snapshot",{state:gameState});renderGame()}
function sendIntent(row,col){if(kicked||!gameState||gameState.winner)return;send("intent",{playerId:me.id,side:me.side,slot:selectedSlot,row,col})}
function hostTick(){if(!gameState||gameState.winner)return;const now=Date.now(),dt=Math.min(.35,(now-gameState.lastTick)/1000);gameState.lastTick=now;if(now>=gameState.endsAt)return finishByScore();for(const d of gameState.derps){if(d.hp<=0)continue;const du=DERPS[d.type];const targets=gameState.plants.filter(p=>p.hp>0&&p.row===d.row).sort((a,b)=>b.col-a.col);const t=targets.filter(p=>p.col<=d.x+0.7).sort((a,b)=>b.col-a.col)[0];if(t&&Math.abs(d.x-t.col)<.75){if(now-d.lastHit>900){t.hp-=du.damage;d.lastHit=now}}else d.x-=du.speed*dt;if(d.x<-.25)return finish("Derps win","A derp reached the plant base.")}
for(const p of gameState.plants){if(p.hp<=0)continue;const pu=PLANTS[p.type];if(pu.damage<=0)continue;const targets=gameState.derps.filter(d=>d.hp>0&&d.x>p.col&&Math.abs(d.row-p.row)<=2).sort((a,b)=>a.x-b.x);const t=targets[0];if(t&&now-p.lastShot>pu.rate*1000){t.hp-=pu.damage;p.lastShot=now}}
gameState.plants=gameState.plants.filter(x=>x.hp>0);gameState.derps=gameState.derps.filter(x=>x.hp>0);if(gameState.glow.plants<=0&&!gameState.plants.length)return finish("Derps win","Plants ran out of Glow and units.");if(gameState.glow.derps<=0&&!gameState.derps.length)return finish("Plants win","Derps ran out of Glow and units.");send("snapshot",{state:gameState});renderGame()}
function finishByScore(){const pv=gameState.glow.plants+gameState.plants.reduce((n,x)=>n+x.hp,0),dv=gameState.glow.derps+gameState.derps.reduce((n,x)=>n+x.hp,0);finish(pv===dv?"Draw":pv>dv?"Plants win":"Derps win",`Time expired. Plant score ${Math.round(pv)}, Derp score ${Math.round(dv)}.`)}
function finish(title,text){if(gameState?.winner)return;gameState.winner=title;clearInterval(simTimer);send("round-end",{title,text});endRound(title,text)}
function endRound(title,text){$("game").classList.add("hidden");$("result").classList.remove("hidden");$("resultTitle").textContent=title;$("resultText").textContent=text}
function renderGame(){if(!gameState)return;document.querySelectorAll("#battlefield > .derp-piece").forEach(e=>e.remove());$("plantGlow").textContent=Math.max(0,Math.floor(gameState.glow.plants));$("derpGlow").textContent=Math.max(0,Math.floor(gameState.glow.derps));const left=Math.max(0,gameState.endsAt-Date.now()),m=Math.floor(left/60000),s=Math.floor(left/1000)%60;$("timer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;const board=$("board");board.innerHTML="";for(let r=0;r<5;r++)for(let c=0;c<9;c++){const cell=document.createElement("div");cell.className="cell";cell.onclick=()=>sendIntent(r,c);board.appendChild(cell)}for(const p of gameState.plants){const u=PLANTS[p.type],cell=board.children[p.row*9+p.col];cell.insertAdjacentHTML("beforeend",`<div class="piece"><img src="${u.img}"><span class="hp"><i style="width:${100*p.hp/p.maxHp}%"></i></span></div>`)}for(const d of gameState.derps){const u=DERPS[d.type],piece=document.createElement("div");piece.className="piece derp-piece";piece.style.width="10%";piece.style.height="18%";piece.style.left=`${7+d.x*9.5}%`;piece.style.top=`${10+d.row*16.3}%`;piece.innerHTML=`<img src="${u.img}"><span class="hp"><i style="width:${100*d.hp/d.maxHp}%"></i></span>`;$("battlefield").appendChild(piece)} }

Object.entries(BACKGROUNDS).forEach(([v,n])=>$("backgroundSelect").insertAdjacentHTML("beforeend",`<option value="${v}">${n}</option>`));$("timeLimit").oninput=e=>$("timeOut").textContent=`${e.target.value} minute${e.target.value==1?"":"s"}`;$("startGlow").oninput=e=>$("glowOut").textContent=e.target.value;
$("createBtn").onclick=()=>enter(true,false);$("joinBtn").onclick=()=>enter(false,false);$("createLocalBtn").onclick=()=>enter(true,true);$("joinLocalBtn").onclick=()=>enter(false,true);$("rerollBtn").onclick=()=>{if((rerolls[me.id]??3)<=0)return;send("reroll-request",{id:me.id,slot:selectedSlot})};$("readyBtn").onclick=()=>{readyMap[me.id]=!readyMap[me.id];send("ready-change",{id:me.id,ready:readyMap[me.id]});if(isHost){hostPrepare();if(assigned.length>=2&&assigned.every(x=>readyMap[x.id]))startGame()}$("readyBtn").textContent=readyMap[me.id]?"Unready":"Ready"};$("leaveBtn").onclick=()=>location.reload();$("forfeitBtn").onclick=()=>send("forfeit",{side:me.side});$("backLobbyBtn").onclick=()=>location.reload();window.addEventListener("beforeunload",()=>localChannel?.close());setInterval(()=>{if(gameState&&!gameState.winner)renderGame()},500);
