(() => {
"use strict";
const DRAFT="td_mod_studio_draft_v2", MODS="td_mods_v1", ACTIVE="td_active_mods_v1";
const $=id=>document.getElementById(id), clone=x=>JSON.parse(JSON.stringify(x));
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f));}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let pack=read(DRAFT,null)||basePack(); let selected={levels:0,things:0,enemies:0};
function freshPack(){return{format:"THINGS_DERPS_MOD_V1",id:"my-mod",name:"My Things & Derps Mod",author:"Br Wood",version:"1.0.0",description:"My custom Things & Derps expansion.",created:new Date().toISOString(),updated:new Date().toISOString(),content:{levels:[],things:[],enemies:[],worlds:[],chapters:[],backgrounds:{},images:{},audio:{tracks:{}},gameplay:{},currency:{},board:{},defaultLoadout:[],theme:{background:"#050914",panel:"#0b1324",text:"#ffffff",accent:"#17345f",outline:"#ffffff",radius:8,font:"Arial, sans-serif"}},assets:[]};}
function basePack(){const b=clone(window.TD_BASE_CATALOG||{}),p=freshPack();p.id="editable-base-game";p.name="Editable Things & Derps Base Game";p.description="A complete editable copy of the current game data. Change existing IDs to override the base game safely.";p.content.levels=b.levels||[];p.content.things=b.things||[];p.content.enemies=b.enemies||[];p.content.worlds=b.worlds||[];p.content.chapters=b.chapters||[];p.content.backgrounds=b.backgrounds||{};p.content.images=b.images||{};p.content.audio=b.audio||{tracks:{}};p.content.gameplay=b.gameplay||{};p.content.currency=b.currency||{};p.content.board=b.board||{};p.content.defaultLoadout=b.defaultLoadout||[];p.content.theme=b.theme||p.content.theme;return p;}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),1800)}
function slug(v){return String(v||"mod").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48)||"mod"}
function syncMeta(){pack.name=$("modName").value.trim()||"Untitled Mod";pack.id=slug($("modId").value||pack.name);$("modId").value=pack.id;pack.author=$("modAuthor").value.trim();pack.version=$("modVersion").value.trim()||"1.0.0";pack.description=$("modDescription").value.trim();pack.updated=new Date().toISOString();updateCounts()}
function loadMeta(){$("modName").value=pack.name;$("modId").value=pack.id;$("modAuthor").value=pack.author;$("modVersion").value=pack.version;$("modDescription").value=pack.description}
function saveDraft(){syncMeta();syncTheme();write(DRAFT,pack);toast("Creator draft saved")}
function installCurrent(enable=true){syncMeta();syncTheme();const list=read(MODS,[]),i=list.findIndex(x=>x.id===pack.id);if(i>=0)list[i]=clone(pack);else list.push(clone(pack));write(MODS,list);if(enable){const a=new Set(read(ACTIVE,[]));a.add(pack.id);write(ACTIVE,[...a])}renderInstalled();toast("Mod installed and enabled")}
function showTab(name){document.querySelectorAll(".tabpage").forEach(x=>x.classList.toggle("on",x.id===`${name}Tab`));document.querySelectorAll("#tabs button").forEach(x=>x.classList.toggle("on",x.dataset.tab===name));if(name==="manager")renderInstalled()}
function updateCounts(){$("chapterCount").textContent=(pack.content.chapters||[]).length;$("worldCount").textContent=(pack.content.worlds||[]).length;$("levelCount").textContent=pack.content.levels.length;$("thingCount").textContent=pack.content.things.length;$("enemyCount").textContent=pack.content.enemies.length;$("assetCount").textContent=pack.assets.length}
function options(items,current){return items.map(x=>`<option ${x===current?"selected":""}>${esc(x)}</option>`).join("")}
function assetOptions(current){const keep=current&&!pack.assets.some(a=>a.id===current)?`<option value="${esc(current)}" selected>Base image: ${esc(current)}</option>`:"";return `<option value="">No image</option>`+keep+pack.assets.filter(a=>a.type.startsWith("image/")).map(a=>`<option value="${esc(a.id)}" ${a.id===current?"selected":""}>${esc(a.name)}</option>`).join("")}
function addLevel(){pack.content.levels.push({name:`M-${pack.content.levels.length+1}`,title:"New Mod Level",desc:"Made in Creator Studio.",world:1,difficulty:"Custom",startGlow:150,background:"forest",music:"battle",waves:[[{type:"basic",row:2,delay:120}]],lava:[]});selected.levels=pack.content.levels.length-1;renderLevels();updateCounts()}
function renderLevels(){const list=$("levelList"),items=pack.content.levels;list.innerHTML=items.length?items.map((x,i)=>`<button class="${i===selected.levels?"on":""}" data-i="${i}"><b>${esc(x.name)}</b><br><span class="small">${esc(x.title)}</span></button>`).join(""):"<p>No custom levels yet.</p>";list.querySelectorAll("button").forEach(b=>b.onclick=()=>{selected.levels=+b.dataset.i;renderLevels()});const l=items[selected.levels];if(!l){$("levelEditor").innerHTML="<p>Create a level to begin.</p>";return}$("levelEditor").innerHTML=`<div class="formgrid"><label>Level ID / name<input data-f="name" value="${esc(l.name)}"></label><label>Title<input data-f="title" value="${esc(l.title)}"></label><label>World<input data-f="world" type="number" value="${l.world||1}"></label><label>Difficulty<input data-f="difficulty" value="${esc(l.difficulty||"Custom")}"></label><label>Starting Glow<input data-f="startGlow" type="number" value="${l.startGlow||0}"></label><label>Background key<input data-f="background" value="${esc(l.background||"forest")}"></label><label>Music key<input data-f="music" value="${esc(l.music||"battle")}"></label><label class="wide">Description<input data-f="desc" value="${esc(l.desc||"")}"></label></div><div class="sectionhead"><h3>Waves</h3><button id="waveAdd">Add Wave</button></div><div id="waves">${l.waves.map((w,wi)=>waveHtml(w,wi)).join("")}</div><div class="actions"><button id="cloneLevel">Clone</button><button id="deleteLevel" class="danger">Delete Level</button></div>`;
$("levelEditor").querySelectorAll("[data-f]").forEach(input=>input.oninput=()=>{const f=input.dataset.f;l[f]=input.type==="number"?Number(input.value):input.value;renderLevelListOnly()});$("waveAdd").onclick=()=>{l.waves.push([]);renderLevels()};$("cloneLevel").onclick=()=>{const c=clone(l);c.name+=`-copy`;c.title+=` Copy`;items.push(c);selected.levels=items.length-1;renderLevels();updateCounts()};$("deleteLevel").onclick=()=>{if(confirm("Delete this level?")){items.splice(selected.levels,1);selected.levels=Math.max(0,selected.levels-1);renderLevels();updateCounts()}};hookWaves(l)}
function renderLevelListOnly(){const buttons=$("levelList").querySelectorAll("button");const l=pack.content.levels[selected.levels];if(buttons[selected.levels]&&l)buttons[selected.levels].innerHTML=`<b>${esc(l.name)}</b><br><span class="small">${esc(l.title)}</span>`}
function waveHtml(w,wi){return `<div class="wave"><div class="wavehead"><b>Wave ${wi+1}</b><div><button data-addenemy="${wi}">Add Enemy</button><button class="danger" data-delwave="${wi}">X</button></div></div>${w.map((e,ei)=>`<div class="enemyrow"><label>Enemy ID<select data-e="${wi},${ei},type">${pack.content.enemies.map(x=>`<option value="${esc(x.id)}" ${x.id===e.type?"selected":""}>${esc(x.id)} — ${esc(x.name)}</option>`).join("")}</select></label><label>Row<input type="number" min="0" max="4" data-e="${wi},${ei},row" value="${e.row}"></label><label>Delay<input type="number" data-e="${wi},${ei},delay" value="${e.delay}"></label><button class="danger" data-dele="${wi},${ei}">X</button></div>`).join("")}</div>`}
function hookWaves(l){$("waves").querySelectorAll("[data-addenemy]").forEach(b=>b.onclick=()=>{l.waves[+b.dataset.addenemy].push({type:"basic",row:2,delay:120});renderLevels()});$("waves").querySelectorAll("[data-delwave]").forEach(b=>b.onclick=()=>{l.waves.splice(+b.dataset.delwave,1);if(!l.waves.length)l.waves=[[]];renderLevels()});$("waves").querySelectorAll("[data-dele]").forEach(b=>b.onclick=()=>{const[w,e]=b.dataset.dele.split(",").map(Number);l.waves[w].splice(e,1);renderLevels()});$("waves").querySelectorAll("[data-e]").forEach(input=>input.oninput=()=>{const[w,e,f]=input.dataset.e.split(",");l.waves[+w][+e][f]=input.type==="number"?Number(input.value):input.value})}
function addThing(){pack.content.things.push({id:`thing${pack.content.things.length+1}`,name:"New Thing",cost:100,hp:100,img:"",desc:"A custom Thing.",role:"Shooter",shooter:true,fireType:"straight",shootCooldown:120,projectileDamage:25,projectileSpeed:5,placementCooldown:180});selected.things=pack.content.things.length-1;renderThings();updateCounts()}
function addEnemy(){pack.content.enemies.push({id:`enemy${pack.content.enemies.length+1}`,name:"New Enemy",hp:120,speed:.18,damage:12,img:"",size:1,tags:["derp"],rangedShooter:false,boss:false,desc:"A custom enemy."});selected.enemies=pack.content.enemies.length-1;renderEnemies();updateCounts()}
function renderThings(){renderEntity("things",$("thingList"),$("thingEditor"),[{f:"id",n:"ID"},{f:"name",n:"Name"},{f:"cost",n:"Cost",t:"number"},{f:"hp",n:"HP",t:"number"},{f:"role",n:"Role"},{f:"img",n:"Image",t:"asset"},{f:"desc",n:"Description",wide:1},{f:"shooter",n:"Shooter",t:"bool"},{f:"producer",n:"Producer",t:"bool"},{f:"wall",n:"Wall",t:"bool"},{f:"fireType",n:"Fire type"},{f:"shootCooldown",n:"Shoot cooldown",t:"number"},{f:"projectileDamage",n:"Projectile damage",t:"number"},{f:"projectileSpeed",n:"Projectile speed",t:"number"},{f:"produceAmount",n:"Produce amount",t:"number"},{f:"produceCooldown",n:"Produce cooldown",t:"number"},{f:"placementCooldown",n:"Placement cooldown",t:"number"}])}
function renderEnemies(){renderEntity("enemies",$("enemyList"),$("enemyEditor"),[{f:"id",n:"ID"},{f:"name",n:"Name"},{f:"hp",n:"HP",t:"number"},{f:"speed",n:"Speed",t:"number",step:"0.01"},{f:"damage",n:"Damage",t:"number"},{f:"size",n:"Size",t:"number",step:"0.05"},{f:"img",n:"Image",t:"asset"},{f:"tags",n:"Tags, comma separated"},{f:"rangedShooter",n:"Ranged",t:"bool"},{f:"boss",n:"Boss",t:"bool"},{f:"flying",n:"Flying",t:"bool"},{f:"shootCooldown",n:"Shot cooldown",t:"number"},{f:"shotDamage",n:"Shot damage",t:"number"},{f:"shotSpeed",n:"Shot speed",t:"number"},{f:"desc",n:"Description",wide:1}])}
function renderEntity(type,list,editor,fields){const items=pack.content[type],idx=selected[type];list.innerHTML=items.length?items.map((x,i)=>`<button class="${i===idx?"on":""}" data-i="${i}"><b>${esc(x.id)}</b><br><span class="small">${esc(x.name)}</span></button>`).join(""):"<p>Nothing here yet.</p>";list.querySelectorAll("button").forEach(b=>b.onclick=()=>{selected[type]=+b.dataset.i;type==="things"?renderThings():renderEnemies()});const x=items[idx];if(!x){editor.innerHTML="<p>Create one to begin.</p>";return}editor.innerHTML=`<div class="formgrid">${fields.map(q=>fieldHtml(q,x[q.f])).join("")}</div><div class="actions"><button id="cloneEntity">Clone</button><button id="deleteEntity" class="danger">Delete</button></div>`;editor.querySelectorAll("[data-f]").forEach(input=>input.oninput=()=>{const f=input.dataset.f,t=input.dataset.t;let v=t==="number"?Number(input.value):t==="bool"?input.value==="true":input.value;if(f==="tags")v=String(v).split(",").map(s=>s.trim()).filter(Boolean);x[f]=v;const b=list.querySelectorAll("button")[idx];if(b)b.innerHTML=`<b>${esc(x.id)}</b><br><span class="small">${esc(x.name)}</span>`});$("cloneEntity").onclick=()=>{const c=clone(x);c.id+=`Copy`;c.name+=` Copy`;items.push(c);selected[type]=items.length-1;type==="things"?renderThings():renderEnemies();updateCounts()};$("deleteEntity").onclick=()=>{if(confirm("Delete this item?")){items.splice(idx,1);selected[type]=Math.max(0,idx-1);type==="things"?renderThings():renderEnemies();updateCounts()}}}
function fieldHtml(q,v){const cls=q.wide?' class="wide"':'';if(q.t==="bool")return `<label${cls}>${q.n}<select data-f="${q.f}" data-t="bool"><option value="false" ${!v?"selected":""}>No</option><option value="true" ${v?"selected":""}>Yes</option></select></label>`;if(q.t==="asset")return `<label${cls}>${q.n}<select data-f="${q.f}">${assetOptions(v)}</select></label>`;const shown=q.f==="tags"&&Array.isArray(v)?v.join(", "):v??"";return `<label${cls}>${q.n}<input data-f="${q.f}" data-t="${q.t||"text"}" type="${q.t==="number"?"number":"text"}" ${q.step?`step="${q.step}"`:""} value="${esc(shown)}"></label>`}
function renderChapters(){const area=$("chapterList"),items=pack.content.chapters||(pack.content.chapters=[]);area.innerHTML=items.map((c,i)=>`<article><label>Chapter name<input data-c="${i},name" value="${esc(c.name)}"></label><label>ID<input data-c="${i},id" value="${esc(c.id)}"></label><label>World IDs, comma separated<input data-c="${i},worlds" value="${esc((c.worlds||[]).join(", "))}"></label><label>Description<textarea data-c="${i},description">${esc(c.description||"")}</textarea></label><button class="danger" data-delchapter="${i}">Delete</button></article>`).join("")||"<p>No chapters yet.</p>";area.querySelectorAll("[data-c]").forEach(input=>input.oninput=()=>{const[i,f]=input.dataset.c.split(",");pack.content.chapters[+i][f]=f==="worlds"?input.value.split(",").map(x=>x.trim()).filter(Boolean):input.value});area.querySelectorAll("[data-delchapter]").forEach(b=>b.onclick=()=>{pack.content.chapters.splice(+b.dataset.delchapter,1);renderChapters();updateCounts()})}
function renderSettings(){const c=pack.content,e=$("settingsEditor");const groups=[['Gameplay','gameplay'],['Currency','currency'],['Board','board']];e.innerHTML=groups.map(([title,key])=>`<section class="settingsGroup"><h3>${title}</h3><div class="formgrid">${Object.entries(c[key]||{}).map(([f,v])=>`<label>${esc(f)}<input data-setting="${key},${f}" type="${typeof v==='number'?'number':'text'}" value="${esc(Array.isArray(v)?v.join(', '):v)}"></label>`).join('')}</div></section>`).join('')+`<section class="settingsGroup"><h3>Default Loadout</h3><label>Thing IDs, comma separated<input id="defaultLoadoutInput" value="${esc((c.defaultLoadout||[]).join(', '))}"></label></section><section class="settingsGroup"><h3>Background Keys</h3><div class="keytable">${Object.entries(c.backgrounds||{}).map(([k,v])=>`<label>${esc(k)}<input data-map="backgrounds,${esc(k)}" value="${esc(v)}"></label>`).join('')}</div></section><section class="settingsGroup"><h3>Music Tracks</h3><div class="keytable">${Object.entries(c.audio?.tracks||{}).map(([k,v])=>`<label>${esc(k)}<input data-map="audio,${esc(k)}" value="${esc(v)}"></label>`).join('')}</div></section>`;e.querySelectorAll('[data-setting]').forEach(input=>input.oninput=()=>{const[g,f]=input.dataset.setting.split(',');const old=c[g][f];c[g][f]=typeof old==='number'?Number(input.value):input.value});e.querySelectorAll('[data-map]').forEach(input=>input.oninput=()=>{const[g,f]=input.dataset.map.split(',');if(g==='audio'){c.audio=c.audio||{tracks:{}};c.audio.tracks[f]=input.value}else{c[g][f]=input.value}});$("defaultLoadoutInput").oninput=ev=>c.defaultLoadout=ev.target.value.split(',').map(x=>x.trim()).filter(Boolean)}
function renderWorlds(){const area=$("worldList");area.innerHTML=pack.content.worlds.map((w,i)=>`<article><label>Name<input data-w="${i},name" value="${esc(w.name)}"></label><label>ID<input data-w="${i},id" value="${esc(w.id)}"></label><label>Level prefix<input data-w="${i},prefix" value="${esc(w.prefix||"")}"></label><label>Chapter ID<input data-w="${i},chapter" value="${esc(w.chapter||"")}"></label><label>Description<textarea data-w="${i},description">${esc(w.description||"")}</textarea></label><button class="danger" data-delworld="${i}">Delete</button></article>`).join("")||"<p>No world groups yet.</p>";area.querySelectorAll("[data-w]").forEach(input=>input.oninput=()=>{const[i,f]=input.dataset.w.split(",");pack.content.worlds[+i][f]=input.value});area.querySelectorAll("[data-delworld]").forEach(b=>b.onclick=()=>{pack.content.worlds.splice(+b.dataset.delworld,1);renderWorlds()})}
function syncTheme(){for(const f of ["Background","Panel","Text","Accent","Outline","Radius","Font"]){const key=f.toLowerCase();pack.content.theme[key]=$("theme"+f).type==="number"?Number($("theme"+f).value):$("theme"+f).value}}
function loadTheme(){const t=pack.content.theme;for(const f of ["Background","Panel","Text","Accent","Outline","Radius","Font"]){const key=f.toLowerCase();$("theme"+f).value=t[key]??""}previewTheme()}
function previewTheme(){syncTheme();const t=pack.content.theme,p=$("themePreview");p.style.setProperty("--preview-bg",t.background);p.style.setProperty("--preview-text",t.text);p.style.setProperty("--preview-accent",t.accent);p.style.setProperty("--preview-outline",t.outline);p.style.setProperty("--preview-radius",`${t.radius}px`);p.style.setProperty("--preview-font",t.font)}
function addAssets(files){[...files].forEach(file=>{const reader=new FileReader();reader.onload=()=>{pack.assets.push({id:uid("asset"),name:file.name,type:file.type||"application/octet-stream",data:reader.result});renderAssets();updateCounts()};reader.readAsDataURL(file)})}
function renderAssets(){const area=$("assetList");area.innerHTML=pack.assets.map((a,i)=>`<article>${a.type.startsWith("image/")?`<img src="${a.data}" alt="">`:a.type.startsWith("audio/")?`<audio controls src="${a.data}"></audio>`:""}<h3>${esc(a.name)}</h3><p class="small">ID: ${esc(a.id)}</p><div class="actions"><button data-copyasset="${i}">Copy ID</button><button class="danger" data-delasset="${i}">Delete</button></div></article>`).join("")||"<p>No assets yet.</p>";area.querySelectorAll("[data-copyasset]").forEach(b=>b.onclick=()=>navigator.clipboard?.writeText(pack.assets[+b.dataset.copyasset].id));area.querySelectorAll("[data-delasset]").forEach(b=>b.onclick=()=>{pack.assets.splice(+b.dataset.delasset,1);renderAssets();updateCounts()})}
function renderInstalled(){const list=read(MODS,[]),active=new Set(read(ACTIVE,[])),area=$("installedList");area.innerHTML=list.map((m,i)=>`<article><h3>${esc(m.name)}</h3><p>${esc(m.description||"")}</p><p class="small">${esc(m.id)} • v${esc(m.version)} • ${esc(m.author)}</p><div class="actions"><button data-toggle="${i}">${active.has(m.id)?"Disable":"Enable"}</button><button data-edit="${i}">Edit</button><button class="danger" data-delmod="${i}">Delete</button></div></article>`).join("")||"<p>No installed mods. Save this mod or import one.</p>";area.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>{const m=list[+b.dataset.toggle],set=new Set(read(ACTIVE,[]));set.has(m.id)?set.delete(m.id):set.add(m.id);write(ACTIVE,[...set]);renderInstalled();toast("Reload the game to apply changes")});area.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>{pack=clone(list[+b.dataset.edit]);write(DRAFT,pack);reloadAll();showTab("dashboard");toast("Loaded mod into editor")});area.querySelectorAll("[data-delmod]").forEach(b=>b.onclick=()=>{const m=list[+b.dataset.delmod];if(confirm(`Delete ${m.name}?`)){list.splice(+b.dataset.delmod,1);write(MODS,list);const set=new Set(read(ACTIVE,[]));set.delete(m.id);write(ACTIVE,[...set]);renderInstalled()}})}
function exportPack(){syncMeta();syncTheme();const blob=new Blob([JSON.stringify(pack,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${pack.id}.tadmod`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importPack(file){const r=new FileReader();r.onload=()=>{try{const m=JSON.parse(r.result);if(m.format!=="THINGS_DERPS_MOD_V1")throw Error("Not a Things & Derps V1 mod");const list=read(MODS,[]),i=list.findIndex(x=>x.id===m.id);if(i>=0)list[i]=m;else list.push(m);write(MODS,list);renderInstalled();toast("Mod imported") }catch(e){alert(`Import failed: ${e.message}`)}};r.readAsText(file)}
function reloadAll(){pack.content.chapters=pack.content.chapters||[];pack.content.worlds=pack.content.worlds||[];pack.content.gameplay=pack.content.gameplay||{};pack.content.currency=pack.content.currency||{};pack.content.board=pack.content.board||{};pack.content.backgrounds=pack.content.backgrounds||{};pack.content.audio=pack.content.audio||{tracks:{}};loadMeta();loadTheme();renderChapters();renderLevels();renderThings();renderEnemies();renderWorlds();renderSettings();renderAssets();renderInstalled();updateCounts()}
function hooks(){document.querySelectorAll("#tabs button").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>showTab(b.dataset.go));["modName","modId","modAuthor","modVersion","modDescription"].forEach(id=>$(id).oninput=syncMeta);$("savePack").onclick=()=>{saveDraft();installCurrent(true)};$("exportPack").onclick=exportPack;$("newPack").onclick=()=>{if(confirm("Start a blank mod? Your installed mods will not be deleted.")){pack=freshPack();write(DRAFT,pack);selected={levels:0,things:0,enemies:0};reloadAll()}};$("loadBase").onclick=()=>{if(confirm("Replace the current draft with a fresh editable copy of every base-game item?")){pack=basePack();write(DRAFT,pack);selected={levels:0,things:0,enemies:0};reloadAll();toast("Loaded every base-game item")}};$("addChapter").onclick=()=>{pack.content.chapters.push({id:`chapter-${pack.content.chapters.length+1}`,name:"New Chapter",description:"",worlds:[]});renderChapters();updateCounts()};$("addLevel").onclick=addLevel;$("addThing").onclick=addThing;$("addEnemy").onclick=addEnemy;$("addWorld").onclick=()=>{pack.content.worlds.push({id:`world-${pack.content.worlds.length+1}`,name:"New World",prefix:"M"});renderWorlds()};["themeBackground","themePanel","themeText","themeAccent","themeOutline","themeRadius","themeFont"].forEach(id=>$(id).oninput=previewTheme);$("assetInput").onchange=e=>{addAssets(e.target.files);e.target.value=""};$("importInput").onchange=e=>{if(e.target.files[0])importPack(e.target.files[0]);e.target.value=""}}
hooks();reloadAll();
})();
