// PAD Modder v2.8 - Clown Multiverse Fangame Forge
"use strict";
const STORAGE_KEY="pad_custom_levels_v1";
const PLANT_KEY="pad_fangame_plants_v28";
const DERP_KEY="pad_fangame_derps_v28";
const BACKGROUNDS=["forest","desert","cloud","milkyway","chess","debugHill","matrixGrid","glitchArchive","clownBrown","clownBlood","clownChaos","clownTeal","clownGreen","theEdge"];
const MUSIC=["world1","battle","desert","menu","victory","finalBoss","clownMultiverse","edge"];
const ENEMIES=["basic","armored","fast","assasinRover","mechaDerp","wetDerp","droneGun","droneSaw","alien","alienGun","alienShotgunner","alienGod","alienFinalBoss","guntankBoi","unknownCubes","ragingBoi","cardboardTank","eggPowerDerp","curseDerp","puppetDerp","clownCar","clownDerp","edgeVoid"];
const MAX_WAVES=15,MAX_ENEMIES_PER_WAVE=12;
let current=makeDefaultLevel();
let savedLevels=loadJson(STORAGE_KEY,[]);
let savedPlants=loadJson(PLANT_KEY,[]);
let savedDerps=loadJson(DERP_KEY,[]);
function clamp(num,min,max){return Math.max(min,Math.min(max,Number(num)||0));}
function $(id){return document.getElementById(id);} 
function loadJson(k,fallback){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(fallback));}catch{return fallback;}}
function saveJson(k,v){localStorage.setItem(k,JSON.stringify(v));}
function makeDefaultLevel(){return{name:"Custom-1",title:"My Weird Level",desc:"Made in PAD Modder.",world:5,difficulty:"Hard",startGlow:200,background:"forest",music:"battle",waves:[[{type:"basic",row:2,delay:120}]],lava:[],tags:["custom"]};}
function encodeLevel(level){return btoa(unescape(encodeURIComponent(JSON.stringify(level))));}
function decodeLevel(code){return JSON.parse(decodeURIComponent(escape(atob(code.trim()))));}
function fillDropdowns(){const bg=$("backgroundSelect"),music=$("musicSelect");bg.innerHTML="";music.innerHTML="";for(const item of BACKGROUNDS)bg.append(new Option(item,item));for(const item of MUSIC)music.append(new Option(item,item));}
function sanitizeLevel(level){level.name=String(level.name||"Custom-1").slice(0,24);level.title=String(level.title||"Untitled Level").slice(0,50);level.desc=String(level.desc||"Made in PAD Modder.").slice(0,160);level.world=clamp(level.world,0,99);level.difficulty=String(level.difficulty||"Medium");level.startGlow=clamp(level.startGlow,0,9000);if(!BACKGROUNDS.includes(level.background))level.background="forest";if(!MUSIC.includes(level.music))level.music="battle";level.tags=Array.isArray(level.tags)?level.tags:["custom"];level.lava=Array.isArray(level.lava)?level.lava:[];level.lava=level.lava.filter(p=>Array.isArray(p)&&p.length>=2).map(p=>[clamp(p[0],0,8),clamp(p[1],0,4)]).filter((p,i,a)=>a.findIndex(o=>o[0]===p[0]&&o[1]===p[1])===i);level.waves=Array.isArray(level.waves)?level.waves.slice(0,MAX_WAVES):[[]];if(!level.waves.length)level.waves.push([]);level.waves=level.waves.map(w=>Array.isArray(w)?w.slice(0,MAX_ENEMIES_PER_WAVE).map(e=>({type:ENEMIES.includes(e.type)?e.type:"basic",row:clamp(e.row,0,4),delay:clamp(e.delay,30,2000)})):[]);return level;}
function syncFormFromLevel(){sanitizeLevel(current);$("levelName").value=current.name;$("levelTitle").value=current.title;$("levelDesc").value=current.desc;$("worldNumber").value=current.world;$("difficultySelect").value=current.difficulty;$("startGlow").value=current.startGlow;$("backgroundSelect").value=current.background;$("musicSelect").value=current.music;renderLavaGrid();renderWaves();renderSavedLevels();updatePreview();}
function syncLevelFromForm(){current.name=($("levelName").value||"Custom-1").trim().slice(0,24);current.title=($("levelTitle").value||"Untitled Level").trim().slice(0,50);current.desc=($("levelDesc").value||"Made in PAD Modder.").trim().slice(0,160);current.world=clamp($("worldNumber").value,0,99);current.difficulty=$("difficultySelect").value;current.startGlow=clamp($("startGlow").value,0,9000);current.background=$("backgroundSelect").value;current.music=$("musicSelect").value;sanitizeLevel(current);updatePreview();}
function renderLavaGrid(){const grid=$("lavaGrid");grid.innerHTML="";const lavaSet=new Set(current.lava.map(([c,r])=>`${c},${r}`));for(let r=0;r<5;r++){for(let c=0;c<9;c++){const key=`${c},${r}`,btn=document.createElement("button");btn.className=`lava-cell ${lavaSet.has(key)?"on":""}`;btn.textContent=`${c},${r}`;btn.onclick=()=>toggleLava(c,r);grid.appendChild(btn);}}}
function toggleLava(c,r){const i=current.lava.findIndex(p=>p[0]===c&&p[1]===r);if(i>=0)current.lava.splice(i,1);else current.lava.push([c,r]);syncLevelFromForm();renderLavaGrid();}
function enemyOptions(type){return ENEMIES.map(e=>`<option value="${e}" ${e===type?"selected":""}>${e}</option>`).join("");}
function renderWaves(){const area=$("wavesArea");area.innerHTML="";current.waves.forEach((wave,wi)=>{const card=document.createElement("section");card.className="wave-card";card.innerHTML=`<div class="wave-head"><h3>Wave ${wi+1}</h3><div><button class="btn ghost" data-add="${wi}">Add Enemy</button> <button class="btn ghost danger" data-remove-wave="${wi}">Remove Wave</button></div></div>`;if(wave.length===0)card.insertAdjacentHTML("beforeend",`<p class="hint">No enemies yet. Add one.</p>`);wave.forEach((enemy,ei)=>{card.insertAdjacentHTML("beforeend",`<div class="enemy-row"><label>Enemy<select data-wave="${wi}" data-enemy="${ei}" data-field="type">${enemyOptions(enemy.type)}</select></label><label>Row<input type="number" min="0" max="4" value="${enemy.row}" data-wave="${wi}" data-enemy="${ei}" data-field="row"></label><label>Delay<input type="number" min="30" max="2000" value="${enemy.delay}" data-wave="${wi}" data-enemy="${ei}" data-field="delay"></label><button title="Remove enemy" data-remove-enemy="${wi},${ei}">X</button></div>`);});area.appendChild(card);});area.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addEnemy(Number(b.dataset.add)));area.querySelectorAll("[data-remove-wave]").forEach(b=>b.onclick=()=>removeWave(Number(b.dataset.removeWave)));area.querySelectorAll("[data-remove-enemy]").forEach(b=>b.onclick=()=>{const[wi,ei]=b.dataset.removeEnemy.split(",").map(Number);current.waves[wi].splice(ei,1);syncLevelFromForm();renderWaves();});area.querySelectorAll("input,select").forEach(input=>input.oninput=()=>{const wi=Number(input.dataset.wave),ei=Number(input.dataset.enemy),f=input.dataset.field;if(!current.waves[wi]?.[ei])return;if(f==="type")current.waves[wi][ei].type=input.value;if(f==="row")current.waves[wi][ei].row=clamp(input.value,0,4);if(f==="delay")current.waves[wi][ei].delay=clamp(input.value,30,2000);syncLevelFromForm();});}
function addWave(){if(current.waves.length>=MAX_WAVES)return alert("Max 15 waves.");current.waves.push([]);syncLevelFromForm();renderWaves();}
function removeWave(i){if(current.waves.length<=1)return alert("A level needs at least 1 wave.");current.waves.splice(i,1);syncLevelFromForm();renderWaves();}
function addEnemy(wi){const w=current.waves[wi];if(!w)return;if(w.length>=MAX_ENEMIES_PER_WAVE)return alert("Max 12 enemies per wave.");w.push({type:"basic",row:2,delay:120+w.length*120});syncLevelFromForm();renderWaves();}
function renderSavedLevels(){const list=$("savedLevels");list.innerHTML="";if(!savedLevels.length){list.innerHTML=`<p class="hint">No saved levels yet.</p>`;return;}savedLevels.forEach((level,i)=>{const item=document.createElement("div");item.className="saved-item";item.innerHTML=`<b>${level.name||`Custom-${i+1}`}</b><div>${level.title||"Untitled Level"}</div><div class="saved-actions"><button data-load="${i}">Load</button><button data-copy="${i}">Copy Code</button><button data-delete="${i}">Delete</button></div>`;list.appendChild(item);});list.querySelectorAll("[data-load]").forEach(b=>b.onclick=()=>{current=JSON.parse(JSON.stringify(savedLevels[Number(b.dataset.load)]));syncFormFromLevel();});list.querySelectorAll("[data-copy]").forEach(b=>{b.onclick=()=>{const i=Number(b.dataset.copy);$("shareBox").value=encodeLevel(savedLevels[i]);$("shareBox").select();navigator.clipboard?.writeText($("shareBox").value).catch(()=>{});};});list.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.delete);if(!confirm("Delete this saved level?"))return;savedLevels.splice(i,1);saveJson(STORAGE_KEY,savedLevels);renderSavedLevels();});}
function saveCurrentLevel(){syncLevelFromForm();const copy=JSON.parse(JSON.stringify(current));sanitizeLevel(copy);const i=savedLevels.findIndex(l=>l.name===copy.name);if(i>=0){if(!confirm("Replace saved level with the same name?"))return;savedLevels[i]=copy;}else savedLevels.push(copy);saveJson(STORAGE_KEY,savedLevels);renderSavedLevels();alert("Level saved.");}
function updatePreview(){const p=$("jsonPreview");if(p)p.textContent=JSON.stringify(sanitizeLevel(JSON.parse(JSON.stringify(current))),null,2);}
function exportCurrent(){syncLevelFromForm();$("shareBox").value=encodeLevel(current);$("shareBox").select();navigator.clipboard?.writeText($("shareBox").value).catch(()=>{});}
function importFromBox(){try{current=sanitizeLevel(decodeLevel($("shareBox").value));syncFormFromLevel();alert("Imported level.");}catch(err){alert("Import failed.");console.warn(err);}}
function plantConfig(){const fire=$("plantFire").value;const cfg={id:$("plantId").value.trim()||"myPlant",group:$("plantGroup").value,name:$("plantName").value.trim()||"My Plant",cost:clamp($("plantCost").value,0,9999),hp:clamp($("plantHp").value,1,9999),img:$("plantImg").value.trim()||"assets/myplant.png",desc:$("plantDesc").value.trim(),role:$("plantRole").value.trim()||"Plant",unlockAt:$("plantUnlock").value.trim()||undefined,placementCooldown:180};if(fire!=="none")Object.assign(cfg,{shooter:true,fireType:fire,shootCooldown:clamp($("plantCooldown").value,20,9999),projectileDamage:clamp($("plantDamage").value,0,9999),projectileSpeed:clamp($("plantSpeed").value,1,40)});return cfg;}
function derpConfig(){return{id:$("derpId").value.trim()||"myDerp",group:$("derpGroup").value,name:$("derpName").value.trim()||"My Derp",hp:clamp($("derpHp").value,1,99999),speed:clamp($("derpSpeed").value,0.01,10),damage:clamp($("derpDamage").value,0,9999),img:$("derpImg").value.trim()||"assets/myderp.png",size:clamp($("derpSize").value,0.1,10),tags:$("derpTags").value.split(",").map(s=>s.trim()).filter(Boolean),rangedShooter:$("derpRanged").value==="true",boss:$("derpBoss").value==="true",desc:$("derpDesc").value.trim()};}
function updateMakers(){if($("plantPreview"))$("plantPreview").textContent=JSON.stringify(plantConfig(),null,2);if($("derpPreview"))$("derpPreview").textContent=JSON.stringify(derpConfig(),null,2);}
function savePlant(){const c=plantConfig();const i=savedPlants.findIndex(x=>x.id===c.id);if(i>=0)savedPlants[i]=c;else savedPlants.push(c);saveJson(PLANT_KEY,savedPlants);updatePack();alert("Plant config saved.");}
function saveDerp(){const c=derpConfig();const i=savedDerps.findIndex(x=>x.id===c.id);if(i>=0)savedDerps[i]=c;else savedDerps.push(c);saveJson(DERP_KEY,savedDerps);updatePack();alert("Derp config saved.");}
function pack(){return{format:"PAD_FANGAME_PACK_V1",created:new Date().toISOString(),levels:savedLevels,plants:savedPlants,derps:savedDerps,notes:"Paste configs into PAD or a fangame loader. Textures are path-based."};}
function updatePack(){if($("packBox"))$("packBox").value=JSON.stringify(pack(),null,2);}
function copyText(text){navigator.clipboard?.writeText(text).catch(()=>{});}
function showTab(name){for(const el of ["level","plant","derp","pack"]){$(el+"Tab").classList.toggle("hidden",el!==name);}document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("on",b.dataset.tab===name));if(name==="pack")updatePack();}
function hookEvents(){["levelName","levelTitle","levelDesc","worldNumber","difficultySelect","startGlow","backgroundSelect","musicSelect"].forEach(id=>$(id).addEventListener("input",syncLevelFromForm));$("newLevelBtn").onclick=()=>{if(!confirm("Start a new level? Unsaved changes will be lost."))return;current=makeDefaultLevel();syncFormFromLevel();};$("saveBtn").onclick=saveCurrentLevel;$("exportBtn").onclick=exportCurrent;$("importBtn").onclick=importFromBox;$("addWaveBtn").onclick=addWave;$("clearWavesBtn").onclick=()=>{if(confirm("Clear all waves?")){current.waves=[[]];syncLevelFromForm();renderWaves();}};$("clearLavaBtn").onclick=()=>{current.lava=[];syncLevelFromForm();renderLavaGrid();};document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll("#plantTab input,#plantTab select,#derpTab input,#derpTab select").forEach(i=>i.addEventListener("input",updateMakers));$("makePlantBtn").onclick=savePlant;$("makeDerpBtn").onclick=saveDerp;$("copyPlantBtn").onclick=()=>copyText(JSON.stringify(plantConfig(),null,2));$("copyDerpBtn").onclick=()=>copyText(JSON.stringify(derpConfig(),null,2));$("refreshPackBtn").onclick=updatePack;$("copyPackBtn").onclick=()=>copyText($("packBox").value);$("clearPackBtn").onclick=()=>{if(confirm("Clear saved custom plant/derp configs?")){savedPlants=[];savedDerps=[];saveJson(PLANT_KEY,[]);saveJson(DERP_KEY,[]);updatePack();}};}
function boot(){fillDropdowns();hookEvents();syncFormFromLevel();updateMakers();updatePack();console.log("PAD Modder v2.8 Clown Multiverse Fangame Forge loaded.");}
boot();
